apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: backstage
type: Opaque
data:
  username: cG9zdGdyZXMK
  password: cm9vdAo=
  POSTGRES_USERNAME: cG9zdGdyZXMK
  POSTGRES_PASSWORD: cm9vdAo=
  POSTGRES_DATABASE: YmFja3N0YWdlX3BsdWdpbl9hcHAK
  database: YmFja3N0YWdlX3BsdWdpbl9hcHAK
  POSTGRES_DB: YmFja3N0YWdlX3BsdWdpbl9hcHAK
